DROP DATABASE IF EXISTS `rental-oc-project-3`;

CREATE DATABASE `rental-oc-project-3`;

USE `rental-oc-project-3`;


CREATE TABLE users (
    id integer AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE rentals (
    id integer AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    surface DOUBLE NOT NULL,
    price DOUBLE NOT NULL,
    picture VARCHAR(255) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    owner_id integer NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE messages (
    id integer AUTO_INCREMENT PRIMARY KEY,
    message VARCHAR(2000) NOT NULL,
    user_id integer NOT NULL,
    rental_id integer NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (rental_id) REFERENCES rentals(id) ON DELETE CASCADE
);

